### ISSUE TITLE
Give created reminders their own event in the logs channel

### ISSUE THREAD

**Issue by Zenorax** [medeor413/Red_Star_Plugins#19]
Example:

**ANALYSIS: User Zenorax#1706 has set a reminder at `year-month-day @ hour:minute:second` in #channel . ANALYSIS: Contents: `REMIND MESSAGE | year-month-day @ hour:minute:second | MESSAGE DESTINATION | RECURRING FREQENCY`**

**Comment by rubellyte** [comment]
I don't really see a particular reason for this to be implemented? And it also raises an issue with private reminders not really being private.

**Comment by Zenorax** [comment]
Didn't even think about that it would make private reminders not private anymore. That's a good point.

**Comment by rubellyte** [comment]
This belongs on the main repository as both the Reminder and Logger plugins are part of core, and is not a desired feature regardless.
